const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1500, location: "Phuket", country: "Thailand",
    category: "Surfing",
    geometry: { type: "Point", cordinates: [98.3923, 7.8804] },
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1200, location: "Berlin", country: "Germany",
    category: "Design",
    geometry: { type: "Point", cordinates: [13.405, 52.52] },
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1000, location: "Queenstown", country: "New Zealand",
    category: "Mountains",
    geometry: { type: "Point", cordinates: [168.6626, -45.0312] },
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of rolling hills in this beautifully restored villa. Explore the vineyards and countryside.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2500, location: "Cappadocia", country: "Turkey",
    category: "Countryside",
    geometry: { type: "Point", cordinates: [34.8289, 38.6431] },
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 800, location: "Amazon Rainforest", country: "Brazil",
    category: "Treehouses",
    geometry: { type: "Point", cordinates: [-60.0217, -3.4653] },
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2000, location: "Zanzibar", country: "Tanzania",
    category: "Surfing",
    geometry: { type: "Point", cordinates: [39.3599, -6.1659] },
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 900, location: "Interlaken", country: "Switzerland",
    category: "Lakefront",
    geometry: { type: "Point", cordinates: [7.8632, 46.6863] },
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3500, location: "Hong Kong", country: "China",
    category: "Design",
    geometry: { type: "Point", cordinates: [114.1694, 22.3193] },
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet nestled in the Alps.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3000, location: "Niseko", country: "Japan",
    category: "Arctic",
    geometry: { type: "Point", cordinates: [140.6868, 42.8044] },
  },
  {
    title: "Safari Lodge in the Bush",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Big Five up close.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 4000, location: "Kruger National Park", country: "South Africa",
    category: "National parks",
    geometry: { type: "Point", cordinates: [31.5609, -23.9884] },
  },
  {
    title: "Historic Canal House",
    description: "Stay in a piece of history in this beautifully preserved canal house in an iconic city district.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1800, location: "Bruges", country: "Belgium",
    category: "Rooms",
    geometry: { type: "Point", cordinates: [3.2247, 51.2093] },
  },
  {
    title: "Private Island Retreat",
    description: "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 10000, location: "Bora Bora", country: "French Polynesia",
    category: "OMG",
    geometry: { type: "Point", cordinates: [-151.7415, -16.5004] },
  },
  {
    title: "Charming Countryside Cottage",
    description: "Escape to the picturesque countryside in this quaint and charming cottage with a thatched roof.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1200, location: "Hallstatt", country: "Austria",
    category: "Countryside",
    geometry: { type: "Point", cordinates: [13.6493, 47.5622] },
  },
  {
    title: "Historic Riad",
    description: "Step back in time in this elegantly restored traditional riad with a stunning inner courtyard.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2200, location: "Marrakech", country: "Morocco",
    category: "Desert",
    geometry: { type: "Point", cordinates: [-7.9811, 31.6295] },
  },
  {
    title: "Beachfront Bungalow",
    description: "Relax on the sandy shores in this beautiful beachfront bungalow with a private pool and ocean views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1800, location: "Palawan", country: "Philippines",
    category: "Surfing",
    geometry: { type: "Point", cordinates: [118.7384, 9.8349] },
  },
  {
    title: "Mountain View Cabin",
    description: "Enjoy breathtaking mountain views from this cozy cabin surrounded by pristine wilderness.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1500, location: "Patagonia", country: "Argentina",
    category: "Mountains",
    geometry: { type: "Point", cordinates: [-72.9312, -41.1335] },
  },
  {
    title: "Colonial Apartment",
    description: "Step into the glamour of colonial architecture in this beautifully appointed old-town apartment.",
    image: { filename: "listingimage", url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1600, location: "Cartagena", country: "Colombia",
    category: "Rooms",
    geometry: { type: "Point", cordinates: [-75.5144, 10.391] },
  },
  {
    title: "Tropical Villa",
    description: "Escape to a tropical paradise in this luxurious villa with a private infinity pool and jungle views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3000, location: "Ubud", country: "Indonesia",
    category: "Treehouses",
    geometry: { type: "Point", cordinates: [115.2625, -8.5069] },
  },
  {
    title: "Historic Castle Stay",
    description: "Live like royalty in this historic castle. Explore rugged landscapes and ancient history.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 4000, location: "Prague", country: "Czech Republic",
    category: "OMG",
    geometry: { type: "Point", cordinates: [14.4378, 50.0755] },
  },
  {
    title: "Desert Oasis",
    description: "Experience luxury in the middle of the desert in this opulent oasis with a private pool and starlit skies.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 5000, location: "Wadi Rum", country: "Jordan",
    category: "Desert",
    geometry: { type: "Point", cordinates: [36.5841, 29.5752] },
  },
  {
    title: "Rustic Log Cabin",
    description: "Unplug and unwind in this cozy log cabin surrounded by ancient forests and crystal-clear rivers.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1100, location: "Lapland", country: "Finland",
    category: "Arctic",
    geometry: { type: "Point", cordinates: [27.0, 68.0] },
  },
  {
    title: "Beachfront Villa",
    description: "Enjoy the crystal-clear waters of the Aegean in this beautiful beachfront villa on a stunning island.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2500, location: "Santorini", country: "Greece",
    category: "Surfing",
    geometry: { type: "Point", cordinates: [25.4615, 36.3932] },
  },
  {
    title: "Eco-Friendly Treehouse Retreat",
    description: "Stay in an eco-friendly treehouse nestled deep in the forest. It's the perfect escape for nature lovers.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 750, location: "Daintree Rainforest", country: "Australia",
    category: "Treehouses",
    geometry: { type: "Point", cordinates: [145.3211, -16.1703] },
  },
  {
    title: "Historic Old Town Apartment",
    description: "Experience rich heritage and cobblestone streets from this beautifully restored old-town apartment.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1600, location: "Dubrovnik", country: "Croatia",
    category: "Rooms",
    geometry: { type: "Point", cordinates: [18.0944, 42.6507] },
  },
  {
    title: "Modern Apartment",
    description: "Explore the vibrant city life from this modern and centrally located apartment with stunning skyline views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2000, location: "Singapore", country: "Singapore",
    category: "Design",
    geometry: { type: "Point", cordinates: [103.8198, 1.3521] },
  },
  {
    title: "Lakefront Cabin",
    description: "Spend your days by the breathtaking lake surrounded by snow-capped peaks and alpine meadows.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1200, location: "Banff", country: "Canada",
    category: "Lakefront",
    geometry: { type: "Point", cordinates: [-115.5708, 51.1784] },
  },
  {
    title: "Luxury Overwater Villa",
    description: "Indulge in luxury in this overwater villa with stunning views of the turquoise lagoon.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 6000, location: "Maldives", country: "Maldives",
    category: "OMG",
    geometry: { type: "Point", cordinates: [73.2207, 3.2028] },
  },
  {
    title: "Ski Chalet",
    description: "Hit the slopes in style with this luxurious ski chalet in one of the world's finest ski resorts.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 4000, location: "Chamonix", country: "France",
    category: "Arctic",
    geometry: { type: "Point", cordinates: [6.8696, 45.9237] },
  },
  {
    title: "Secluded Beach House",
    description: "Escape to a secluded beach house on a pristine coastline. Surf, relax, and unwind in paradise.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1800, location: "Algarve", country: "Portugal",
    category: "Surfing",
    geometry: { type: "Point", cordinates: [-8.2245, 37.0179] },
  },
  {
    title: "Royal Heritage Haveli",
    description: "Stay in a magnificently restored royal haveli surrounded by the golden sands of the Thar Desert.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1477587458883-47145ed94245?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3500, location: "Jaisalmer", country: "India",
    category: "Desert",
    geometry: { type: "Point", cordinates: [70.9083, 26.9157] },
  },
  {
    title: "Houseboat on Dal Lake",
    description: "Drift away on this luxurious traditional houseboat on the serene Dal Lake.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2800, location: "Srinagar", country: "India",
    category: "Lakefront",
    geometry: { type: "Point", cordinates: [74.7973, 34.0837] },
  },
  {
    title: "Cliffside Tea Estate Bungalow",
    description: "Wake up to misty mornings and rolling green tea gardens in this charming colonial-era planter's bungalow.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1800, location: "Ooty", country: "India",
    category: "Mountains",
    geometry: { type: "Point", cordinates: [76.6950, 11.4102] },
  },
  {
    title: "Backwater Luxury Villa",
    description: "Unwind in this stunning villa perched on the edge of Kerala's tranquil backwaters.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2200, location: "Alleppey", country: "India",
    category: "Lakefront",
    geometry: { type: "Point", cordinates: [76.3388, 9.4981] },
  },
  {
    title: "Himalayan Mountain Lodge",
    description: "Perched high in the Himalayas, this cozy mountain lodge offers spectacular views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2000, location: "Leh", country: "India",
    category: "Mountains",
    geometry: { type: "Point", cordinates: [77.5771, 34.1526] },
  },
  {
    title: "Beachfront Goan Villa",
    description: "Enjoy the laid-back charm of Goa from this breezy beachfront villa with a private pool.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3000, location: "North Goa", country: "India",
    category: "Surfing",
    geometry: { type: "Point", cordinates: [73.7463, 15.5524] },
  },
  {
    title: "Jungle Safari Camp",
    description: "Immerse yourself in the wild heart of India from this luxury tented camp.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 4500, location: "Ranthambore", country: "India",
    category: "National parks",
    geometry: { type: "Point", cordinates: [76.5026, 26.0173] },
  },
  {
    title: "Palace Suite by the Lake",
    description: "Live like a Maharaja in this opulent palace suite overlooking the shimmering waters of Lake Pichola.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1599661046289-e31897846e41?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 5500, location: "Udaipur", country: "India",
    category: "OMG",
    geometry: { type: "Point", cordinates: [73.6833, 24.5854] },
  },
  {
    title: "Riverside Bamboo Cottage",
    description: "Stay in a charming bamboo cottage nestled on the banks of the Brahmaputra river.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1542401886-65d6c61db217?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1400, location: "Kaziranga", country: "India",
    category: "National parks",
    geometry: { type: "Point", cordinates: [93.3700, 26.6400] },
  },
  {
    title: "Ancient Temple Town Retreat",
    description: "Soak in centuries of spirituality and culture from this beautifully restored heritage home.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1561361058-c24cecae35ca?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1600, location: "Varanasi", country: "India",
    category: "Camping",
    geometry: { type: "Point", cordinates: [82.9739, 25.3176] },
  },
];

module.exports = { data: sampleListings };